CURSOR_0_POSITION = (51, 51)
CURSOR_1_POSITION = (51, 61)
CURSOR_2_POSITION = (51, 71)
CURSOR_3_POSITION = (51, 81)

DOTS_ON_LEVEL = 240
POINTS_PER_DOT = 10
POINTS_PER_ENERGETIC = 50
BASE_POINTS_PER_FRUIT = 100
FRUIT_DOTS_EATEN_APPEAR = (70, 170)
FRUIT_TIME = 100
FRUIT_POSITION = (42, 51)
FIRST_GHOST_EATEN_POINTS = 200
NEXT_GHOST_EATEN_MULTIPLIER = 2
EXTRA_LIFE_POINTS_N = 10000
PER_LEVEL_SPEED_UP = 1.5

PACMAN_START_POSITION = (41, 69)

SCATTER_TIME = 100
CHASE_TIME = 700
FRIGHTENED_TIME = 70
KILLED_TARGET = (42, 33)

BLINKY_START_POSITION = (42, 33)
BLINKY_SCATTER_TARGET = (81, 0)

PINKY_START_POSITION = (42, 39)
PINKY_SCATTER_TARGET = (0, 0)

INKY_START_POSITION = (39, 39)
INKY_SCATTER_TARGET = (81, 89)
INKY_POINTS_EATEN_START = 30

CLYDE_START_POSITION = (45, 39)
CLYDE_SCATTER_TARGET = (0, 89)
CLYDE_POINTS_EATEN_START = 80

MAP_FILENAME = "Map.txt"
GRAPHICS_DIR = "./Graphics/"
CURSOR_FILENAME = GRAPHICS_DIR + "!Cursor.txt"
LIVES_FILENAME = GRAPHICS_DIR + "!Life.txt"
FRUIT_FILENAME = GRAPHICS_DIR + "!Fruit.txt"

PACMAN_CLOSED_FILENAME = GRAPHICS_DIR + "!PacmanClosed.txt"
PACMAN_UP_FILENAME = GRAPHICS_DIR + "!PacmanUp.txt"
PACMAN_DOWN_FILENAME = GRAPHICS_DIR + "!PacmanDown.txt"
PACMAN_LEFT_FILENAME = GRAPHICS_DIR + "!PacmanLeft.txt"
PACMAN_RIGHT_FILENAME = GRAPHICS_DIR + "!PacmanRight.txt"

GHOST_0_FILENAME = GRAPHICS_DIR + "!Ghost0.txt"
GHOST_1_FILENAME = GRAPHICS_DIR + "!Ghost1.txt"

CHARACTERS_FILENAME = GRAPHICS_DIR + "!Characters.txt"
ENERGETIC_FILENAME = GRAPHICS_DIR + "!Energetic.txt"
MAP_GRAPHICS_FILENAME = GRAPHICS_DIR + "!Map.txt"
MAIN_MENU_FILENAME = GRAPHICS_DIR + "!MainMenu.txt"
HIGH_SCORES_FILENAME = "HighScores.txt"
